### ISSUE TITLE
CSS File Not Present

### ISSUE THREAD

**Issue by shoebilyas123** [dimensionhq/vortex#4]
Whenever I try to:
`import "@hydralite/vortex/dist/style.css";`
it throws an error that the file is not present. Please fix this asap because the styles are not applicable at all.

**Comment by VarunPotti** [comment]
Hey @shoebilyas123, we are fixing this issue (by EOD), I will reply to the same message if I have completed fixing this.

**Comment by VarunPotti** [comment]
Hey @shoebilyas123, we have fixed the issue, you should now be able to use vortex with `npm install @dimensionhq/vortex` and use vortex as described in our docs.
